/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as M6RouteImport } from './routes/m6'
import { Route as M5RouteImport } from './routes/m5'
import { Route as M4RouteImport } from './routes/m4'
import { Route as M3RouteImport } from './routes/m3'
import { Route as M2RouteImport } from './routes/m2'
import { Route as M1RouteImport } from './routes/m1'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const M6Route = M6RouteImport.update({
  id: '/m6',
  path: '/m6',
  getParentRoute: () => rootRouteImport,
} as any)
const M5Route = M5RouteImport.update({
  id: '/m5',
  path: '/m5',
  getParentRoute: () => rootRouteImport,
} as any)
const M4Route = M4RouteImport.update({
  id: '/m4',
  path: '/m4',
  getParentRoute: () => rootRouteImport,
} as any)
const M3Route = M3RouteImport.update({
  id: '/m3',
  path: '/m3',
  getParentRoute: () => rootRouteImport,
} as any)
const M2Route = M2RouteImport.update({
  id: '/m2',
  path: '/m2',
  getParentRoute: () => rootRouteImport,
} as any)
const M1Route = M1RouteImport.update({
  id: '/m1',
  path: '/m1',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/m1': typeof M1Route
  '/m2': typeof M2Route
  '/m3': typeof M3Route
  '/m4': typeof M4Route
  '/m5': typeof M5Route
  '/m6': typeof M6Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/m1': typeof M1Route
  '/m2': typeof M2Route
  '/m3': typeof M3Route
  '/m4': typeof M4Route
  '/m5': typeof M5Route
  '/m6': typeof M6Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/m1': typeof M1Route
  '/m2': typeof M2Route
  '/m3': typeof M3Route
  '/m4': typeof M4Route
  '/m5': typeof M5Route
  '/m6': typeof M6Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/m1' | '/m2' | '/m3' | '/m4' | '/m5' | '/m6'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/m1' | '/m2' | '/m3' | '/m4' | '/m5' | '/m6'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/m1'
    | '/m2'
    | '/m3'
    | '/m4'
    | '/m5'
    | '/m6'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  M1Route: typeof M1Route
  M2Route: typeof M2Route
  M3Route: typeof M3Route
  M4Route: typeof M4Route
  M5Route: typeof M5Route
  M6Route: typeof M6Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/m6': {
      id: '/m6'
      path: '/m6'
      fullPath: '/m6'
      preLoaderRoute: typeof M6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m5': {
      id: '/m5'
      path: '/m5'
      fullPath: '/m5'
      preLoaderRoute: typeof M5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m4': {
      id: '/m4'
      path: '/m4'
      fullPath: '/m4'
      preLoaderRoute: typeof M4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m3': {
      id: '/m3'
      path: '/m3'
      fullPath: '/m3'
      preLoaderRoute: typeof M3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m2': {
      id: '/m2'
      path: '/m2'
      fullPath: '/m2'
      preLoaderRoute: typeof M2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m1': {
      id: '/m1'
      path: '/m1'
      fullPath: '/m1'
      preLoaderRoute: typeof M1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  M1Route: M1Route,
  M2Route: M2Route,
  M3Route: M3Route,
  M4Route: M4Route,
  M5Route: M5Route,
  M6Route: M6Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
